backends:
  bedrock:
    enabled: true
    models:
      mistral_large:
        model_id: mistral.mistral-large-2402-v1:0
        max_tokens: 1024
        temperature: 0.3
        top_p: 0.9
        top_k: 50
      llama3_70b:
        model_id: arn:aws:bedrock:us-east-1:324037276468:inference-profile/us.meta.llama3-3-70b-instruct-v1:0
        max_gen_len: 1024
        temperature: 0.5
        top_p: 0.9
      deepseek_r1:
        model_id: arn:aws:bedrock:us-east-1:324037276468:inference-profile/us.deepseek.r1-v1:0
        max_tokens: 1024
        temperature: 0.4
        top_p: 0.9
      claude3_7_sonnet:
        model_id: us.anthropic.claude-3-7-sonnet-20250219-v1:0
        max_tokens: 1024
        top_k: 250
        stop_sequences: []
        temperature: 1
        top_p: 0.999
prompts:
  validation:
    system: |
      You are a code analysis expert. Output JSON only: ["language", ...].
      Identify programming languages in the provided files based on file extensions and content (e.g., Python: 'def', 'import'; TypeScript: 'function', ': string'; JavaScript: 'function', 'var', 'const').
      Include all initially detected languages unless file content clearly contradicts them.
      Exclude non-languages (e.g., "llm", "sonarqube").
      No explanations or markdown.
    user: |
      Files: {file_list}
      Initially detected languages: {detected_languages}
      Return a JSON array of confirmed languages (e.g., ["Python", "TypeScript", "JavaScript"]), including all initially detected languages unless contradicted by file content.
  security:
    system: |
      You are a security expert. Output JSON only:
      [] or [{"issue": "string", "type": "string", "severity": "low|medium|high", "confidence": integer (1-5), "file": "string", "recommendation": "string"}].
      Do not include text explanations or markdown.
    user: |
      Analyze for vulnerabilities:
      - SonarQube: {sonar_data}
      - Code: {code_samples}
      Return JSON array of issues with type, severity, confidence (1-5), file, recommendation.
  quality:
    system: |
      You are a code quality expert. Output JSON only:
      {"maintainability_score": integer (0-100), "code_smells": integer, "doc_coverage": integer (0-100)}.
      Return exactly this JSON structure. Do not include text, markdown, or other formats.
    user: |
      Evaluate quality:
      - SonarQube: {sonar_data}
      - Code: {code_samples}
      Return JSON with maintainability score (0-100), code smells count, doc coverage (0-100).
  performance:
    system: |
      You are a performance expert. Output JSON only:
      {"rating": integer (0-100), "bottlenecks": ["string"], "optimization_suggestions": ["string"]}.
      Do not include text explanations.
    user: |
      Evaluate performance:
      - SonarQube: {sonar_data}
      - Code: {code_samples}
      Return JSON with rating (0-100), bottlenecks, and optimization suggestions.
  scorecard:
    system: |
      You are an expert code reviewer. Analyze the provided SonarQube data, code samples, specification, and documentation to answer the given question.
      Output JSON only: [{"answer": "string (max 500 chars)", "confidence": integer (1-5, prefer 4-5 for positive evaluations, 3 for partial evidence, 1-2 for no evidence)}].
      Provide concise, accurate answers based on data. Avoid markdown or non-JSON output.
      If data is limited, make reasonable assumptions but lower confidence accordingly.
    user: |
      SonarQube: {sonar_data}
      Code: {code_samples}
      Spec: {spec}
      Docs: {docs}
      Question: {question}
      Category: {category}
      Weight: {weight}
      Answer in JSON array format with a clear evaluation.