name: Deploy to AWS Elastic Beanstalk
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Debug AWS Secrets
        env:
          AWS_ACCESS_KEY_ID: \${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "AWS_ACCESS_KEY_ID is set: \${AWS_ACCESS_KEY_ID:0:4}..."
          echo "AWS_SECRET_ACCESS_KEY is set: \${AWS_SECRET_ACCESS_KEY:0:4}..."
          if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
            echo "Error: AWS secrets are empty"
            exit 1
          fi
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: \${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Verify AWS credentials
        run: |
          aws sts get-caller-identity || { echo "AWS credentials invalid"; exit 1; }
      - name: Install EB CLI
        run: pip install awsebcli --upgrade
      - name: Deploy to Elastic Beanstalk
        run: |
          eb init ai-code-reviewer -p python-3.9 --region us-east-1
          eb use ai-code-reviewer-env
          eb deploy ai-code-reviewer-env --verbose